mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from visualri import views as visualri_views

app_name = 'mysite'

urlpatterns = [
    path('', include('visualri.urls')),
    path('',visualri_views.home, name='home'),
    path('filter/', visualri_views.filter, name='filter'),
    path('result/', visualri_views.result, name='result'),
    path('resultStyle/', visualri_views.resultStyle, name='resultStyle'),
    path('resultColor/', visualri_views.resultColor, name='resultColor'),
    path('styleTransfer/', visualri_views.styleTransfer, name='styleTransfer'),
    path('colorMap', visualri_views.colorMap, name='colorMap'),
    path('download', visualri_views.download, name='download'),
    path('computerVision/',visualri_views.computerVision, name='computerVision'),
    path('imageProcessing/', visualri_views.imageProcessing, name='imageProcessing'),
    path('imageInput/', visualri_views.imageInput, name='imageInput'),
    path('register/',user_views.register, name = 'register'),
    path('profile/',user_views.profile, name = 'profile'),
    path('videostream/',include('videostream.urls')),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'), name = 'login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'), name = 'logout'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/videostream/urls.py
from django.urls import path

from . import views

app_name = 'videostream'
urlpatterns = [
    path('capture', views.capture, name='capture'),
    path('face', views.face, name='face'),
    path('gender', views.gender, name='gender'),
    path('emotion', views.emotion, name='emotion'),
    path('ip_input',views.ip_input,name='ip_input'),
    path('video_feed', views.video_feed, name='video_feed'),
    path('webcam_feed', views.webcam_feed, name='webcam_feed'),
    path('save_image', views.save_image, name='save_image'),
]

mysite/visualri/urls.py
from django.urls import path

from . import views

app_name = 'visualri'
urlpatterns = [

    #path('uploaded/',views.uploaded, name='uploaded'),
    #path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    #path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    #path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/visualri/models.py
'''from django.db import models
from django.utils import timezone

# Create your models here.
class Upload(models.Model):
    date_posted = models.DateTimeField(default=timezone.now)
    title = models.CharField(max_length=100,default='Blurring')
    kernel = models.IntegerField(default=5)
    image = models.ImageField(upload_to='profile_pics',null=True,blank=False)

    def __str__(self):
        return self.title'''

#------------------------------------------Saad Test---------------------------------#
import datetime
from django.core.files.base import ContentFile
from django.db import models
from .utils import get_filtered_image
from PIL import Image
import numpy as np
from io import BytesIO
from django.utils import timezone



class Upload(models.Model):
    # total = Upload.objects.all().count()
    ACTION_CHOICES = [
        ('THRESHOLDING', 'Thresholding'),
        ('BGR', 'BGR'),
        ('HSV', 'HSV'),
        ('GRAYSCALE', 'Grayscale'),
        ('STYLIZATION', 'Stylization'),
        ('DETAIL ENHANCE', 'Detail Enhance'),
        ('COLOR SKETCH', 'Color Sketch'),
        ('BLURRED', 'Bipolar Blur'),
        ('MEDIAN BLUR', 'Median Blur'),
        ('POLARIZE', 'Polarize'),
        ('EDGE PRESERVING FILTER', 'Edge Preserving Filter'),
        ('BRIGHTNESS', 'Brightness'),
        ('CONTRAST', 'Contrast'),
        ('COLORIZED', 'Colorize BW image'),
        ('SUPERRES', 'Super Resolution'),

    ]

    image = models.ImageField(upload_to='profile_pics',null=True,blank=True, default='default.jpg')
    action = models.CharField(max_length=50,choices=ACTION_CHOICES, default='POLARIZE')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(default=timezone.now)
    #kernel = models.IntegerField(default=5)

    def __str__(self):
        return self.action



class Upload_Color_Map(models.Model):
    ACTION_CHOICES = [
        ('0', 'Autumn'),
        ('1', 'Bone'),
        ('8', 'Cool'),
        ('11', 'Hot'),
        ('9', 'HSV'),
        ('2', 'Jet'),
        ('5', 'Ocean'),
        ('12', 'Parula'),
        ('10', 'Pink'),
        ('4', 'Rainbow'),
        ('7', 'Spring'),
        ('6', 'Summer'),
        ('3', 'Winter'),
        ('13', 'Magma'),
        ('14', 'Inferno'),
        ('15', 'Plasma'),
        ('16', 'VIRIDIS'),
        ('17', 'CIVIDIS'),
        ('18', 'Twilight'),
        ('19', 'Twilight_shifted'),
        ('20', 'Turbo'),
        ('21', 'DeepGreen'),
]

    image = models.ImageField(upload_to='images',null=True,blank=True, default='default.jpg')
    action = models.CharField(max_length=50,choices=ACTION_CHOICES, default=15)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.action



class Upload_Style(models.Model):
    ACTION_CHOICES = [
        ('rain', 'rain'),
        ('pink', 'pink'),
        ('traingle', 'triangle'),
        ('gold_black', 'gold_black'),
        ('flame', 'flame'),
        ('Fire_Style', 'Fire_Style'),
        ('landscape', 'landscape'),
        ('feathers', 'feathers'),
        ('candy', 'candy'),
        ('composition_vii', 'composition_vii'),
        ('udnie', 'udnie'),
        ('the_wave', 'the_wave'),
        ('the_scream','the_scream'),
        ('mosaic', 'mosaic'),
        ('la_muse', 'la_muse'),
        ('starry_night', 'starry_night'),
        ]

    image = models.ImageField(upload_to='images',null=True,blank=True, default='default.jpg')
    action = models.CharField(max_length=50,choices=ACTION_CHOICES, default=15)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.action


class Upload_Detect(models.Model):
    image = models.ImageField(upload_to='images',null=True,blank=True, default='default.jpg')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(default=timezone.now)

mysite/visualri/forms.py
'''from django import forms
from .models import Upload

class UploadForm(forms.ModelForm):
    class Meta:
        model = Upload
        fields = ['image','kernel']
        widgets = {
            'kernel': forms.TextInput(attrs={'type': 'range','step':'1','min':'1','max':'10'})
        }
        #widgets = {'parameters': forms.NumberInput(attrs={'type': 'range','step':'0.1'})}'''


#------------------------------------------------Saad Modification---------------------------------#

from django import forms
from django.contrib.auth.decorators import login_required
from .models import Upload, Upload_Color_Map, Upload_Style, Upload_Detect




class UploadForm(forms.ModelForm):
    class Meta:
        model = Upload
        fields = ['image']


class UploadForm_Color_Map(forms.ModelForm):
    class Meta:
        model = Upload_Color_Map
        fields = ['image', 'action']

class UploadForm_Style(forms.ModelForm):
    class Meta:
        model = Upload_Style
        fields = ['image', 'action']

class UploadForm_Detect(forms.ModelForm):
    class Meta:
        model = Upload_Detect
        fields = ['image']


class TextForm(forms.Form):
    btn = forms.CharField(max_length='50')

mysite/visualri/views.py
'''from django.shortcuts import render, redirect
from .forms import UploadForm
from .models import Upload
from PIL import Image
import numpy as np
from .utils import blur,to_data_uri

def index(request):
    #request.method = 'GET'
    print(request.method)
    upload = Upload.objects.latest('date_posted')
    if request.method == 'POST':
        form = UploadForm(request.POST,request.FILES)
        print(form.is_valid())
        #print(form.errors)
        if form.is_valid():
            #print(form.save())
            form.save()
            upload = Upload.objects.latest('date_posted')
            print(upload.kernel)
            #print(form.cleaned_data['image'])
            #model = Upload.get_instance()
            file_name = request.FILES['image']
            pil_img = Image.open(file_name)
            cv_img = np.array(pil_img)
            processed=blur(cv_img,upload.kernel)
            im_pil = Image.fromarray(processed)
            image_uri = to_data_uri(im_pil)
            #print(image_uri)
            return render(request, 'visualri/index.html', {'form': form, 'upload': upload,'image_uri':image_uri})

            #processed_image = model.run_png
            #upload = Upload.objects.latest('date_posted')
            #return render(request, 'visualri/index.html',{'form':form})
    else:
        form = UploadForm()
    return render(request, 'visualri/index.html',{'form':form,'upload':upload})
# Create your views here.

def uploaded(request):
    return render(request,'visualri/uploaded.html')'''

#-------------------------------------------------------SAAD----------------------------------#

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from .forms import UploadForm, TextForm
from .models import Upload
from PIL import Image
import numpy as np
from .utils import get_filtered_image, to_data_uri, style_filter, color_filter
from django.conf import settings
import cv2
import tkinter as tk
from tkinter import simpledialog

image_uri = None

def home(request):
    return render(request, 'visualri/home.html')

def imageProcessing(request):
    global image_uri

    model_instance = Upload.objects.latest('created')

    return render(request, 'visualri/imageProcessing.html', {'model_instance': model_instance})

def computerVision(request):
    return render(request, 'visualri/computerVision.html')

def imageInput(request):
    global image_uri
    		
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            # print(form.save())
            #upload = Upload.objects.latest('created')
            # print(upload.kernel)
            # print(form.cleaned_data['image'])
            # model = Upload.get_instance()
            #file_name = request.FILES['image']
            if bool(request.FILES) == False:
                model_instance = form.save(commit=False)
                if model_instance.action == 'NO_FILTER':
                    pass
                elif model_instance.action == 'COLORIZED':
                    model_instance.image = 'colorized.png'
                elif model_instance.action == 'BLURRED':
                    pass
                elif model_instance.action == 'POLARIZE':
                    pass
                elif model_instance.action == 'COOLING':
                    pass
                elif model_instance.action == 'WARMING':
                    pass
                elif model_instance.action == 'BRIGHTNESS':
                    model_instance.image = 'bright.jpg'
                elif model_instance.action == 'CONTRAST':
                    model_instance.image = 'contrast.png'
                elif model_instance.action =='MEDIAN BLUR':
                    model_instance.image = 'median.jpeg'

                #upload = Upload.objects.latest('created')[0]
                #q= Upload.objects.all().order_by('created')
                #upload=q.reverse()[1]
                try:
                    pil_img = Image.open(model_instance.image[1:])
                except:
                    pil_img = Image.open(model_instance.image)

                cv_img = np.array(pil_img)
                processed=get_filtered_image(cv_img,model_instance.action)
                im_pil = Image.fromarray(processed)
                image_uri = to_data_uri(im_pil)
            else:
                model_instance = form.save()
                file_name = request.FILES['image']
            #upload.image = file_name
                pil_img = Image.open(file_name)
                cv_img = np.array(pil_img)
                processed=get_filtered_image(cv_img,model_instance.action)
                im_pil = Image.fromarray(processed)
                image_uri = to_data_uri(im_pil)
            # print(upload.image)
            #upload.action = 'BLURRED'
            # print(upload.action)
            # uri = upload.save_model()
            # print(a)
            
        #return redirect(request, 'visualri/computerVision.html', {'form': form, 'model_instance': model_instance, 'image_uri': image_uri})
        
        return redirect('imageProcessing')    
        
            # processed_image = model.run_png
            # upload = Upload.objects.latest('date_posted')
            # return render(request, 'visualri/index.html',{'form':form})
    else:
        form = UploadForm()

        return render(request, 'visualri/imageInput.html', {'form': form})



#@login_required
def filter(request):
    
    global action
    #request.method = 'GET'
    
    if request.method == 'POST':

        #print(request.POST)
        form = TextForm(request.POST)

        # print(form.is_valid())
        # print(form.errors)
        
        if form.is_valid():
            action = form.cleaned_data['btn']
            print(action)
            model_instance = Upload.objects.latest('created')
            model_instance.action = action
            model_instance.save()


            print(model_instance.action)

            '''
            #upload = Upload.objects.latest('created')
            # print(upload.kernel)
            # print(form.cleaned_data['image'])
            # model = Upload.get_instance()
            #file_name = request.FILES['image']
            if bool(request.FILES) == False:
                model_instance = form.save(commit=False)
                if model_instance.action == 'NO_FILTER':
                    pass
                elif model_instance.action == 'COLORIZED':
                    model_instance.image = 'colorized.png'
                elif model_instance.action == 'BLURRED':
                    pass
                elif model_instance.action == 'POLARIZE':
                    pass
                elif model_instance.action == 'COOLING':
                    pass
                elif model_instance.action == 'WARMING':
                    pass
                elif model_instance.action == 'BRIGHTNESS':
                    model_instance.image = 'bright.jpg'
                elif model_instance.action == 'CONTRAST':
                    model_instance.image = 'contrast.png'
                elif model_instance.action =='MEDIAN BLUR':
                    model_instance.image = 'median.jpeg'

                #upload = Upload.objects.latest('created')[0]
                #q= Upload.objects.all().order_by('created')
                #upload=q.reverse()[1]
                print(model_instance.image)
                print('asasas')
                print(model_instance.image)
                pil_img = Image.open(model_instance.image)
                cv_img = np.array(pil_img)
                processed=get_filtered_image(cv_img,model_instance.action)
                im_pil = Image.fromarray(processed)
                image_uri = to_data_uri(im_pil)
            else:
                model_instance = form.save()
                file_name = request.FILES['image']
            #upload.image = file_name
                pil_img = Image.open(file_name)
                cv_img = np.array(pil_img)
                processed=get_filtered_image(cv_img,model_instance.action)
                im_pil = Image.fromarray(processed)
                image_uri = to_data_uri(im_pil)
            # print(upload.image)
            #upload.action = 'BLURRED'
            # print(upload.action)
            # uri = upload.save_model()
            # print(a)
            return render(request, 'visualri/index.html',{'form': form, 'model_instance': model_instance, 'image_uri': image_uri})

            # processed_image = model.run_png
            # upload = Upload.objects.latest('date_posted')
            # return render(request, 'visualri/index.html',{'form':form})
    else:
        form = UploadForm()

        return render(request, 'visualri/index.html', {'form': form})

        '''

    return render(request, 'visualri/filter.html')

def colorMap(request):
    return render(request, 'visualri/colorMap.html')

def styleTransfer(request):
    return render(request, 'visualri/styleTransfer.html')

def result(request):

    global image_uri
    global action
    #request.method = 'GET'
    
    if request.method == 'POST':

        #print(request.POST)
        form = TextForm(request.POST)

        # print(form.is_valid())
        # print(form.errors)
        
        if form.is_valid():
            action = form.cleaned_data['btn']
            model_instance = Upload.objects.latest('created')
            model_instance.action = action
            model_instance.save()
            try:
                pil_img = Image.open(model_instance.image.url[1:])
            except:
                pil_img = Image.open(model_instance.image.url)
            cv_img = np.array(pil_img)
            processed=get_filtered_image(cv_img,model_instance.action)
            try:

mysite/visualri/templates/visualri/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Visualri</title>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!-- Load an icon library to show a hamburger menu (bars) on small screens -->
		<link
			rel="stylesheet"
			href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
		/>
		<!--===============================================================================================-->
		<link
			rel="icon"
			type="image/png"
			href="{% static 'visualri/images/icons/visualri.ico' %}"
		/>
		<!--===============================================================================================-->
		<link
			rel="stylesheet"
			type="text/css"
			href="{% static 'visualri/vendor/bootstrap/css/bootstrap.min.css' %}"
		/>
		<!--===============================================================================================-->
		<link
			rel="stylesheet"
			type="text/css"
			href="{% static 'visualri/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}"
		/>
		<!--===============================================================================================-->
		<link
			rel="stylesheet"
			type="text/css"
			href="{% static 'visualri/vendor/animate/animate.css' %}"
		/>
		<!--===============================================================================================-->
		<link
			rel="stylesheet"
			type="text/css"
			href="{% static 'visualri/vendor/css-hamburgers/hamburgers.min.css' %}"
		/>
		<!--===============================================================================================-->
		<link
			rel="stylesheet"
			type="text/css"
			href="{% static 'visualri/vendor/select2/select2.min.css' %}"
		/>
		<!--===============================================================================================-->
		<link
			href="https://unpkg.com/aos@2.3.1/dist/aos.css"
			rel="stylesheet"
		/>
		<!--===============================================================================================-->
		<link
			rel="stylesheet"
			type="text/css"
			href="{% static 'visualri/css/util.css' %}"
		/>
		<link
			rel="stylesheet"
			type="text/css"
			href="{% static 'visualri/css/main.css' %}"
		/>
		<!--===============================================================================================-->
		<style>
			a:hover {
				background: #e9ecef !important;
				color: #343a40 !important;
				border-radius: 5px;
				transition: 0.4s ease-in-out;
			}
		</style>
	</head>
	<body>
		<nav
			class="topnav navbar sticky-top navbar-expand-lg navbar-dark bg-dark"
			id="myTopnav"
		>
			<a
				class="navbar-brand"
				style="font-size: 1.2em; font-family: Comfortaa"
				href="{% url 'home' %}"
				>Visualri</a
			>

			<button
				class="navbar-toggler"
				type="button"
				data-toggle="collapse"
				data-target="#navbarNavAltMarkup"
				aria-controls="navbarNavAltMarkup"
				aria-expanded="false"
				aria-label="Toggle navigation"
			>
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
				<div class="navbar-nav mr-auto color-primary">
					<a
						class="nav-item nav-link fa fa-facebook"
						href="https://www.facebook.com/greatergoodcommunity"
						target="_blank"
					></a>
					<a
						class="nav-item nav-link disabled fa fa-youtube"
						href="https://www.youtube.com/channel/UCGobVlXTTLmfkk4smTgZx1Q"
						target="_blank"
					></a>
				</div>
				{% if user.is_authenticated %}
				<div class="navbar-nav mx-auto">
					<a
						class="nav-item nav-link"
						href="{% url 'computerVision' %}"
						>Computer Vision</a
					>
					<a class="nav-item nav-link" href="{% url 'imageProcessing' %}"
						>Image Processing</a
					>
				</div>
				<div class="navbar-nav ml-auto">
					<a class="nav-item nav-link" href="{% url 'logout' %}"
						>Logout</a
					>
					<a class="nav-item nav-link" href="{% url 'profile' %}"
						>Account</a
					>
				</div>
				{% else %}
				<div class="navbar-nav ml-auto">
					<a class="nav-item nav-link" href="{% url 'login' %}"
						>Login</a
					>
					<a class="nav-item nav-link" href="{% url 'register' %}"
						>Register</a
					>
				</div>
				{% endif %}
			</div>
		</nav>

		<div class="limiter">
			<div
				class="container-login100"
				style="
					background: linear-gradient(-135deg, #c850c0, #00c9ff);
					background: #00c9ff;
					background: linear-gradient(-135deg, #c850c0, #00c9ff);
					background: linear-gradient(-135deg, #e8cbc0, #636fa4);
					background: #636fa4;
				"
			>
				<div class="wrap-login100">
					{% url 'profile' as my_view %} 
					{% if request.path == my_view%}
					<div class="card">
						<img
							src="{{ user.profile.image.url }}"
							style="width: 100%"
						/>
						<h1>{{ user.username }}</h1>
						<p class="title">{{ user.email }}</p>
					</div>
					{% else %}
					<div class="login100-pic js-tilt" data-tilt>
						<img
							src="{% static 'visualri/images/sharingun.webp' %}"
							class="rounded-circle"
							alt="IMG"
						/>
					</div>
					{% endif %} {% block content %}{% endblock %} 
					{% if messages%} 
					{% for message in messages %}
					<div class="alert alert-{{message.tags}}">
						<li class="error">{{ message }}</li>
					</div>
					{% endfor %} {% endif %}
				</div>
			</div>
		</div>

		<div class="container-fluid bg-dark text-light">
			<div class="row py-3">
				<div class="col-5">&copy; Copyrights 2020</div>
				<div class="col-5">Visualri</div>
				<div class="col-2">
					<a href="#" target="_blank">Contact Us</a>
				</div>
			</div>
		</div>

		<!--===============================================================================================-->
		<script src="{% static 'visualri/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
		<!--===============================================================================================-->
		<script src="{% static 'visualri/vendor/bootstrap/js/popper.js' %}"></script>
		<script src="{% static 'visualri/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
		<!--===============================================================================================-->
		<script src="{% static 'visualri/vendor/select2/select2.min.js' %}"></script>
		<!--===============================================================================================-->
		<script src="{% static 'visualri/vendor/tilt/tilt.jquery.min.js' %}"></script>
		<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
		<script>
			$('.js-tilt').tilt({
				scale: 0.9,
			});

			AOS.init();
		</script>
		<!--===============================================================================================-->
		<script src="{% static 'visualri/js/main.js' %}"></script>
	</body>
</html>

mysite/visualri/templates/visualri/computerVision.html
{% extends "visualri/baseHeaderFooter.html" %} 
{% load static %} 
{% block content%}

<!-- Modal 

<div
	class="modal fade"
	id="exampleModal"
	tabindex="-1"
	role="dialog"
	aria-labelledby="exampleModalLabel"
	aria-hidden="true"
>
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Result</h5>
				<button
					type="button"
					class="close"
					data-dismiss="modal"
					aria-label="Close"
				>
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<img
					src="{% static 'visualri/images/robot.png'%}"
					alt=""
					style="object-fit: cover; width: 100%"
				/>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-dark">Download</button>
				<button
					type="button"
					class="btn btn-danger"
					data-dismiss="modal"
				>
					Close
				</button>
			</div>
		</div>
	</div>
</div>


					data-toggle="modal"
					data-target="#exampleModal"

-->

<div class="background" style="background: #e9ecef">
	<div class="container">
		<div class="row">
			<div class="col p-5" style="text-align: center">
				<h1>Select Function</h1>
			</div>
		</div>
		<div class="row" style="align-item: center">
			<div class="col-lg-4 py-3" data-aos="fade-left">
				<div
					class="card p-5"
					style="width: 80%; text-align: center; padding: 20%"
				>
					<h4> Live Gender Detection</h4>
					<p class="text-muted" style="font-size: 15px">
						Face Detection by using IP Camera or Webcam
					</p>
					<br>
					<img
						src="{% static 'visualri\cardImages\main\main\gender.jpg' %}"
						alt=""
						style="width: 100%; object-fit: cover"
					/>
					<br>
					<a
						href="{% url 'videostream:gender' %}"
						class="card-link bg-dark"
						style="
							color: #fff;
							font-weight: bold;
							border-radius: 5px;
							border: 2px solid #343a40;
							padding: 7px;
						"
					>
						Try Now
					</a>
				</div>
			</div>
			<div class="col-lg-4 py-3" data-aos="fade-left">
				<div
					class="card p-5"
					style="width: 80%; text-align: center; padding: 20%"
				>
					<h4> Live Face Detection</h4>
					<p class="text-muted" style="font-size: 15px">
						Face Detection by using IP Camera or Webcam
					</p>
					<br>
					<img
						src="{% static 'visualri\cardImages\main\main\face.jpg' %}"
						alt=""
						style="width: 100%; object-fit: cover"
					/>
					<br>
					<a
						href="{% url 'videostream:face' %}"
						class="card-link bg-dark"
						style="
							color: #fff;
							font-weight: bold;
							border-radius: 5px;
							border: 2px solid #343a40;
							padding: 7px;
						"
					>
						Try Now
					</a>
				</div>
			</div>
			<div class="col-lg-4 py-3" data-aos="fade-left">
			
			<div
					class="card p-5"
					style="width: 80%; text-align: center; padding: 20%"
				>
					<h4> Live Emotion Detection</h4>
					<p class="text-muted" style="font-size: 15px">
						Face Detection by using IP Camera or Webcam
					</p>
					<br>
					<img
						src="{% static 'visualri\cardImages\main\main\emotion.jpg' %}"
						alt=""
						style="width: 100%; object-fit: cover"
					/>
					<br>
					<a
						href="{% url 'videostream:emotion' %}"
						class="card-link bg-dark"
						style="
							color: #fff;
							font-weight: bold;
							border-radius: 5px;
							border: 2px solid #343a40;
							padding: 7px;
						"
					>
						Try Now
					</a>
				</div>

			</div>
		</div>
<br><br>
	</div>
	{% endblock content %}
</div>

mysite/visualri/templates/visualri/imageInput.html
{% extends "visualri/baseHeaderFooter.html" %} 
{% load static %} 
{% block content %}

<div class="background py-4 " style="background: #e9ecef">
	<div class="container px-5" style="background: #fff; border-radius: 20px">
		<div class="row">
			<div class="col-2 p-5" style="text-align: center">
				<a href="{{request.META.HTTP_REFERER}}" class="btn btn-dark">Go back</a>
			</div>
			<div class="col p-5" style="text-align: center">
				<h1>Provide Image</h1>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6" style="text-align: center">
				<h1>Upload Image</h1>
				<p class="text-muted p-4">
					Upload the image on which you want to perform image
					processing on.
				</p>
				<form method="post" class="py-5" enctype="multipart/form-data">
					{% csrf_token %} {{ form.as_p }}
					<div class="form-group">
						<br />
						<button type="submit" class="btn btn-primary">
							Submit
						</button>
					</div>
				</form>
			</div>
			<div class="col-md-6" style="text-align: center;border-left: 1px solid #343a40">
				<h1>Take Picture</h1>
				<p class="text-muted p-4">Take picture from camera to perform image processing.</p>
				<br><br>
				<a  href="{% url 'videostream:capture' %}" class="btn btn-primary">
					Take Picture 
				</a>
				
			</div>
		</div>
		<br>
	</div>
	<br />
	<br />
</div>

{% endblock content %}