mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from visualri import views as visualri_views

app_name = 'mysite'

urlpatterns = [
    path('', include('visualri.urls')),
    path('',visualri_views.home, name='home'),
    path('filter/', visualri_views.filter, name='filter'),
    path('result/', visualri_views.result, name='result'),
    path('resultStyle/', visualri_views.resultStyle, name='resultStyle'),
    path('resultColor/', visualri_views.resultColor, name='resultColor'),
    path('styleTransfer/', visualri_views.styleTransfer, name='styleTransfer'),
    path('colorMap', visualri_views.colorMap, name='colorMap'),
    path('download', visualri_views.download, name='download'),
    path('computerVision/',visualri_views.computerVision, name='computerVision'),
    path('imageProcessing/', visualri_views.imageProcessing, name='imageProcessing'),
    path('imageInput/', visualri_views.imageInput, name='imageInput'),
    path('register/',user_views.register, name = 'register'),
    path('profile/',user_views.profile, name = 'profile'),
    path('videostream/',include('videostream.urls')),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'), name = 'login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'), name = 'logout'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__ (self):
        return f'{self.user.username} Profile'

mysite/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ["username", "email"]

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

mysite/users/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .forms import UserRegistrationForm,UserUpdateForm,ProfileUpdateForm
from django.contrib.auth.decorators import login_required

# Create your views here.

def register(request):
   
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            #username = form.cleaned_data.get('username')
            form.save()
            messages.success(request,f'Your Account has been Created, you can now login')
            return redirect('login')
        else:
            errors = form.errors
            messages.error(request,errors)
    else:
        form = UserRegistrationForm()

    context={
        'form':form,
        }
    return render(request, 'users/register.html',context)



@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST,instance=request.user)
        p_form = ProfileUpdateForm(request.POST,request.FILES,instance=request.user.profile)

        if u_form.is_valid() and u_form.is_valid():
            #username = form.cleaned_data.get('username')
            u_form.save()
            p_form.save()
            
            messages.success(request,f'Your Account has been Updated')
            return redirect('profile')
        else:
            errors = u_form.errors + p_form.errors
            messages.error(request,errors)

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context={
        'u_form':u_form,
        'p_form':p_form
    }
    return render(request,'users/profile.html',context)

mysite/users/templates/users/login.html
{% extends "visualri/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    
			<div class="content-section">
				<form class="login100-form validate-form" method="POST" >
					{% csrf_token %}
					<span class="login100-form-title">
						Member Login
					</span>		
		
		<div class="wrap-input100 form-group" id="div_id_username" >
			<input type="text" name="username" placeholder = "UserName" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" class="input100 textinput textInput form-control" required="" id="id_username"> 
			<span class="focus-input100"></span>
			<span class="symbol-input100">
				<i class="fa fa-user" aria-hidden="true"></i>
			</span>
		</div> 
		<div id="div_id_password" class="wrap-input100 form-group"> 
			<input type="password" placeholder = "Password" name="password" autocomplete="current-password" class="input100 textinput textInput form-control " required="" id="id_password">  
			<span class="focus-input100"></span>
			<span class="symbol-input100">
				<i class="fa fa-lock" aria-hidden="true"></i>
			</span>
		</div> 
		
		
	</fieldset>
	<div class="container-login100-form-btn form-group">
		<button class="login100-form-btn" type="submit" id="submit" formmethod="post">
			Login
		</button>
	</div>
	<br>	

	<div class="text-center p-t-136">
		<a class="txt2" href="{% url 'register' %}">
			Create your Account
			<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
		</a>
	</div>
	
</form>
			
{% endblock content %}

mysite/users/templates/users/logout.html
{% extends "visualri/base.html" %}
{% block content %}

<form class="login100-form validate-form">
	<span class="login100-form-title">
		You have been logged out
	</span>




	<div class="text-center p-t-136">
		<a class="txt2" href="{% url 'login' %}">
			Log In Again
			<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
		</a>
	</div>
	
</form>
 
{% endblock content %}

mysite/users/templates/users/profile.html
{% extends "visualri/base.html" %}
{% load crispy_forms_tags %}
{% block content %}




<form method="POST" class="login100-form validate-form" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="container">
  <fieldset class="form-group">
    <span class="login100-form-title">
      Profile Information
    </span>
        

    <div class="wrap-input100 validate-input" id="div_id_username">
      <input class="input100 form-control"  type="text" name="username" value="{{user.username}}" maxlength="150" required="" id="id_username">          <span class="focus-input100"></span>
      <span class="focus-input100"></span>
      <span class="symbol-input100">
        <i class="fa fa-user" aria-hidden="true"></i>
      </span>
    </div>
    
    <div id="div_id_email" class="wrap-input100 validate-input" data-validate = "Field cannot be empty">
      <input class="input100 form-control" type="email" name="email" value="{{ user.email }}"  required="" id="id_email">
      <span class="focus-input100"></span>
      <span class="symbol-input100">
        <i class="fa fa-envelope" aria-hidden="true"></i>
      </span>
    </div>

    

              

    <div id="div_id_image" class="form-group"> 
      <strong>Current  Image:</strong> <br><a href="{{user.profile.image.url}}" >{{user.profile.image.url}}</a>
    </div>
    <div class="file-input-wrapper">
      <input type="file" name="image" accept="image/*" class="clearablefileinput form-control-file" id="id_image"> 
      <button class="btn-file-input">Update Image</button>
    </div> 
  </fieldset>
  <div class="form-group">
    <button class="btn btn-outline-info" type="submit" formmethod="post">Update</button>
  </div>
  </div>
</form>

    
              
           
			
{% endblock content %}
           
           
          

mysite/users/templates/users/register.html
{% extends "visualri/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    
<form class="login100-form validate-form">
    <!-- <img src="images/signup-bg.jpg" alt=""> -->
    {% csrf_token %}
    <div class="container">
        <form method="POST" class="login100-form validate-form">
            <span class="login100-form-title">
                Create Your Account
                
            </span>
                
            <div class="wrap-input100 validate-input" data-validate = "Field cannot be empty">
                <input class="input100 form-control" type="text" name="username" maxlength="150" required="" id="id_username" placeholder="User Name">
                <span class="focus-input100"></span>
                <span class="symbol-input100">
                    <i class="fa fa-user" aria-hidden="true"></i>
                </span>
            </div>
            <div class="wrap-input100 validate-input" data-validate = "Field cannot be empty">
                <input class="input100 form-control" type="email" name="email" placeholder="Email"   required="" id="id_email">
                <span class="focus-input100"></span>
                <span class="symbol-input100">
                    <i class="fa fa-envelope" aria-hidden="true"></i>
                </span>
            </div>
            
                
            <div class="wrap-input100 validate-input" data-validate = "Password is inappropriate">
                <input class="input100 form-control textinput textInput" name="password1" type="password" placeholder="Password" autocomplete="new-password"  required="" id="id_password1">
                <span class="focus-input100"></span>
                <span class="symbol-input100">
                    <i class="fa fa-lock" aria-hidden="true"></i>
                </span>
            </div>
            <div class="wrap-input100 validate-input" data-validate = "Password doesnot match">
                <input class="input100 form-control textinput textInput" name="password2" type="password" placeholder="Retype Password" autocomplete="new-password"  required="" id="id_password2">
                <span class="focus-input100"></span>
                <span class="symbol-input100">
                    <i class="fa fa-lock" aria-hidden="true"></i>
                </span>
            </div>
            
            <div class="container-login100-form-btn">
                <button class="login100-form-btn" type="submit" id="submit" formmethod="post">
                    Signup
                </button>
            </div>
        </form>
        <p class="loginhere">
        <a href="{% url 'login' %}" class="loginhere-link">Already have an account <i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i></a>
        </p>
    
    </div>
</form>

{% endblock content %}

<input type="password" name="password1" autocomplete="new-password" class="textinput textInput form-control" required="" id="id_password1">  <input type="password" name="password2" autocomplete="new-password" class="textinput textInput form-control" required="" id="id_password2"> <small id="hint_id_password2" class="form-text text-muted">Enter the same password as before, for verification.</small> </div> </div>